-- Finding lesson locations must keep unknown spellbooks, level gaps and encounter conditions visible.
local finder = require('core.blue_finder');
local player = require('core.player');
expect('finder does not load a zone on require', package.loaded['data.zones.900'], nil);
local original = addon.path;
addon.path = FIXTURES_PATH .. '/finder';
MOCK.player.spell_data, MOCK.player.known_spells = true, { [577] = true };
local found = finder.spells('', true, 0);
expect('unlearned filter excludes confirmed known spells', #found, 1);
expect('remaining spell keeps its minimum skill', found[1].spell.min_skill, 25);
MOCK.player.spell_data = false;
finder.changed();
found = finder.spells('', true, 0);
expect('unknown spellbook keeps all possible lessons', #found, 2);
expect('unknown spellbook is labeled', finder.state(found[1].known), 'spellbook unknown');
local read, calls = player.knows_spell, 0;
player.knows_spell = function(id) calls = calls + 1; return read(id); end;
finder.changed();
finder.spells('', true, 0);
finder.spells('foot', true, 0.5);
expect('spellbook reads are cached while searching', calls, 2);
finder.spells('', true, 1);
expect('open finder refreshes its spellbook once per second', calls, 4);
finder.changed(); finder.spells('', true, 1);
expect('spell-list packet can invalidate the cache immediately', calls, 6);
player.knows_spell = read;
local spell = finder.spells('FOOT kick', false, 1)[1].spell;
expect('source places retain both encounter variants', #finder.places(spell, '', nil), 2);
expect('current-zone filter selects only its source places', #finder.places(spell, '', 900), 1);
expect('source levels keep gaps', finder.level_text(spell.monsters[1]), 'Lv 10-12, 25');
expect('missing levels stay unknown', finder.level_text(found[2].spell.monsters[1]), 'Level unknown');
local places = finder.places(spell, 'battlefield', nil);
expect('place search includes encounter conditions', #places, 1);
check('copy includes source restrictions', finder.copy(spell, places):find('Battlefield spawn.', 1, true));
check('copy preserves incomplete coverage', finder.copy(spell, places):find('lesson list is incomplete', 1, true));
check('copy includes source revision', finder.copy(spell, places):find('Fixture source', 1, true));
expect('finder never sends a game command', #MOCK.commands, 0);

local window = require('ui.settings_window');
local settings = require('ui.defaults').make();
require('ui.skins').fill(settings);
window.set_open(true);
MOCK.typing['Find settings'] = 'spell finder';
MOCK.clicks['Blue Magic/Foot Kick (spellbook unknown)##577'] = true;
window.draw(settings, 'test');
check('spell finder is reachable through settings search', MOCK.drew('SPELL FINDER'));
check('selected lesson shows its required skill', MOCK.drew('Minimum Blue Magic skill: 0.'));
MOCK.typing['Blue Magic/Find a monster or zone'] = 'arena';
MOCK.clicks['Blue Magic/Copy places'] = true;
window.draw(settings, 'test');
check('UI copy follows the place search', (MOCK.clipboard or ''):find('Fixture Arena', 1, true));
check('UI copy excludes places hidden by search', not (MOCK.clipboard or ''):find('Fixture Meadow', 1, true));
MOCK.clicks['Blue Magic/Clear##finder_place'] = true;
window.draw(settings, 'test');
check('Clear brings back all places', MOCK.drew('2 matching places.'));
MOCK.player.spell_data, MOCK.player.known_spells = true, { [577] = true, [578] = true };
finder.changed();
window.draw(settings, 'test');
check('learning removes a selected spell from unlearned results', MOCK.drew('0 matching spells.'));
check('an empty result explains the filters', MOCK.drew('Clear the search or turn off Unlearned spells only'));
expect('browsing locations sends no commands', #MOCK.commands, 0);
addon.path = FIXTURES_PATH .. '/missing-finder';
local empty, problem = finder.spells('', true, 5);
expect('missing index returns an empty list', #empty, 0);
check('missing index gives a readable error', problem:find('could not be read', 1, true));
addon.path = original;
return MOCK.report();
