-- Target details follow the visible target without reading client state on its own.
addon.path = FIXTURES_PATH;
dofile(ADDON_DIR .. '/checkmate.lua');
MOCK.fire('load');
local target = require('core.target');
local window = require('ui.settings_window');
MOCK.player.zone, MOCK.player.main_level = 900, 40;
MOCK.zone_in(900);
MOCK.command('/checkmate overlay on');
MOCK.target_monster(1, 'Fixture Goblin');
MOCK.frame();
check('a visible monster has current details', target.current() ~= nil);
MOCK.target.slot0 = 0;
MOCK.frame();
expect('clearing the target clears details even with settings closed', target.current(), nil);
MOCK.target_monster(1, 'Fixture Goblin');
MOCK.frame();
check('retargeting rebuilds the details', target.current() ~= nil);
MOCK.player.pet_index = 99;
MOCK.target_monster(99, 'My Pet');
window.set_open(true);
MOCK.frame();
expect('your own pet does not retain a previous monster', target.current(), nil);
MOCK.player.pet_index = 0;
MOCK.target_monster(1, 'Fixture Goblin');
MOCK.frame();
check('the next monster restores its own details', target.current() and target.current().name == 'Fixture Goblin');
MOCK.player.pet_index = 1;
MOCK.frame();
expect('charming the same target clears its old monster details', target.current(), nil);
MOCK.player.pet_index = 0;
MOCK.frame();
check('charm ending rebuilds the same target without a switch', target.current() and target.current().name == 'Fixture Goblin');
return MOCK.report();
