package.loaded['data.pdif'] = { melee_cap = 2, ranged_cap = 3,
    melee_level_step = 3 / 64, ranged_level_step = 3 / 128, max_level_gap = 38,
    level_corrected_zones = { [103] = true }, defense_effects = { [33] = 'Dia' },
    ignore_ranged_level_effects = { [351] = 'Flashy Shot' } };
local pdif = require('core.pdif');
local function near(label, actual, expected)
    check(label, actual ~= nil and math.abs(actual - expected) < 0.00000001, actual);
end
local same = pdif.bounds(400, 400, 75, 75, 'main');
near('A/D is distinct from the rolled multiplier', same.ratio, 1);
near('equal-level lower bound follows native rounding', same.low, 0.711);
near('equal-level upper bound includes melee randomizer', same.high, 1.365);
near('working curve cap is not the roll maximum', same.cap, 2);
local capped = pdif.bounds(1200, 400, 75, 75, 'main');
near('era saturated melee lower bound', capped.low, 1.625);
near('era saturated melee upper bound', capped.high, 2.49375);
local other = pdif.bounds(1200, 400, 75, 75, 'offhand');
near('off-hand uses the same loaded era curve', other.high, capped.high);
local ranged = pdif.bounds(1200, 400, 75, 75, 'ranged');
near('ranged does not use melee randomizer', ranged.high, 3);
near('ranged cap is separate', ranged.cap, 3);
local crit = pdif.bounds(1200, 400, 75, 75, 'ranged', true);
near('ranged critical factor follows normal roll', crit.high, 3.75);
near('critical addition keeps native floating-point order', pdif.bounds(1, 1000, 75, 95, 'main', true).high, 0.59115);
local spike = pdif.bounds(300, 100, 1, 39, 'main');
near('native early spike retains its level correction', spike.spike, -0.78125);
near('native early spike is included in the envelope', spike.low, -0.78125);
local reversed = pdif.bounds(1082, 320, 1, 39, 'main');
near('reversed rounded endpoints return their first argument', reversed.low, 1.081);
near('reversed endpoints still receive melee randomizer', reversed.high, 1.13505);
near('positive player level gap gives no bonus', pdif.bounds(400, 400, 75, 50, 'main').correction, 0);
near('negative gap is bounded at 38 levels', pdif.bounds(400, 400, 1, 99, 'main').correction, -38 * 3 / 64);
local own = { attack = 558, offhand_attack = 510, ranged_attack = 610, level = 75, zone = 103, buffs = {}, observed_at = 10 };
local mob = { low = 75, high = 75, row = { levels = { [75] = { def = 365 } } } };
local out = pdif.readout(own, mob, 'main');
near('readout exposes the actual attack', out.attack, 558);
near('readout exposes source defense', out.defense_low, 365);
near('readout exposes raw ratio without calling it an average', out.ratio_low, 558 / 365);
check('source defense is always an estimate', out.uncertain);
expect('readout keeps reply provenance', out.observed_at, 10);
check('melee notes explain its extra random factor', table.concat(out.notes, ' '):find('before the melee random factor', 1, true));
check('ranged notes do not claim a melee random factor', not table.concat(pdif.readout(own, mob, 'ranged').notes, ' '):find('melee random factor', 1, true));
mob.low, mob.high, mob.row.levels = 75, 77, { [75] = { def = 365 }, [77] = { def = 385 } };
out = pdif.readout(own, mob, 'main');
near('source level gaps are not invented', out.defense_high, 385);
near('known zone applies correction', out.cap_low, 2 - 2 * 3 / 64);
expect('known correction needs no config warning', out.correction_unknown, nil);
own.zone = 999;
out = pdif.readout(own, mob, 'main');
check('unknown zone setting combines both correction possibilities', out.correction_unknown);
near('unknown setting includes uncorrected cap', out.cap_high, 2);
near('unknown setting also includes corrected cap', out.cap_low, 2 - 2 * 3 / 64);
own.level = 80;
expect('higher player level removes irrelevant setting warning', pdif.readout(own, mob, 'main').correction_unknown, nil);
own.level, own.buffs = 75, { [351] = true };
out = pdif.readout(own, mob, 'ranged');
near('observed Flashy Shot bypasses ranged level correction', out.cap_low, 3);
expect('Flashy Shot removes correction ambiguity', out.correction_unknown, nil);
mob.row.flags, mob.effects = { scripted_defense = true }, { { effect = 33 } };
out = pdif.readout(own, mob, 'main');
check('scripted defense is marked separately', out.scripted);
check('observed defense effects retain uncertainty', table.concat(out.notes, ' '):find('Dia was seen', 1, true));
mob.row.levels[77].def = nil;
expect('missing possible-level defense does not pretend to bound pDIF', pdif.readout(own, mob, 'main').low, nil);
expect('missing source row stays unknown', pdif.readout(own, { low = 75, high = 75 }, 'main').low, nil);
local absent = pdif.readout(nil, mob, 'main', 'The inputs changed.');
expect('a rejected reply stays unknown', absent.low, nil);
expect('a rejected reply keeps its reason', absent.notes[1], 'The inputs changed.');
return MOCK.report();
