local player = require('core.player');
MOCK.items[10], MOCK.items[11], MOCK.items[12], MOCK.items[13] = { Skill = 3 }, { Skill = 2 }, { Skill = 25 }, { Skill = 0 };
MOCK.player.equipment = { [0] = 10, [1] = 11, [2] = 12, [3] = 13 };
MOCK.player.skills = { [3] = 200, [2] = 200, [25] = 200 };
player.forget_attacks();
local first = player.pdif_inputs();
expect('client attack is never an attack-value fallback', first.attack, nil);
expect('snapshot records main weapon skill', first.main_skill, 3);
expect('snapshot records off-hand weapon skill', first.offhand_skill, 2);
expect('snapshot records ranged weapon skill', first.ranged_skill, 25);
expect('snapshot records zone for level correction', first.zone, 103);
check('two equipped one-handed weapons enable off-hand', first.dual_wield);
check('bow and ammunition enable ranged', first.shoots);
local accepted = player.accept_attacks(first, 558, 520, 610, 42);
check('unchanged visible inputs accept a reply', accepted ~= nil);
expect('main attack comes from the server reply', accepted.attack, 558);
expect('off-hand attack is separate', accepted.offhand_attack, 520);
expect('ranged attack is separate', accepted.ranged_attack, 610);
expect('snapshot retains its observation time', accepted.observed_at, 42);
check('unchanged reply remains valid', player.pdif_valid(accepted));
expect('passive lookup reuses matching attack values', player.pdif_inputs().attack, 558);
local function changed(label, mutate, restore)
    local expected = player.pdif_inputs();
    local saved = player.accept_attacks(expected, 558, 520, 610, 42);
    mutate();
    expect(label .. ' invalidates the reply before printing', player.pdif_valid(saved), false);
    expect(label .. ' clears passive attack values', player.pdif_inputs().attack, nil);
    local value, reason = player.accept_attacks(expected, 600, 550, 660, 43);
    expect(label .. ' rejects a reply to older inputs', value, nil);
    check(label .. ' explains the rejected reply', type(reason) == 'string');
    restore();
end
changed('buff change', function() MOCK.player.buffs = { 56 }; end, function() MOCK.player.buffs = {}; end);
changed('gear change', function() MOCK.player.equipment[1] = nil; end, function() MOCK.player.equipment[1] = 11; end);
changed('STR change', function() MOCK.player.stats[0] = 61; end, function() MOCK.player.stats[0] = 60; end);
changed('weapon skill change', function() MOCK.player.skills[3] = 201; end, function() MOCK.player.skills[3] = 200; end);
changed('client attack change', function() MOCK.player.attack = 401; end, function() MOCK.player.attack = 400; end);
changed('level change', function() MOCK.player.main_level = 74; end, function() MOCK.player.main_level = 75; end);
changed('character change', function() MOCK.player.server_id = 1002; end, function() MOCK.player.server_id = 1001; end);
changed('zone change', function() MOCK.player.zone = 104; end, function() MOCK.player.zone = 103; end);
local memory, extra = AshitaCore:GetMemoryManager(), 'first augment';
local inventory = memory.GetInventory;
memory.GetInventory = function(...)
    local bag = inventory(...);
    local item = bag.GetContainerItem;
    bag.GetContainerItem = function(...)
        local value = item(...);
        value.Extra = extra;
        return value;
    end;
    return bag;
end;
changed('same-item augment change', function() extra = 'different augment'; end, function() extra = 'first augment'; end);
memory.GetInventory = inventory;
expect('old accepted snapshot remains unchanged', accepted.attack, 558);
local partial = player.accept_attacks(player.pdif_inputs(), 558, 0, nil, 44);
expect('zero off-hand is unknown', partial.offhand_attack, nil);
expect('missing ranged value remains unknown', partial.ranged_attack, nil);
player.forget_attacks();
expect('zone/reset hook clears attack cache', player.pdif_inputs().attack, nil);
local requests = require('core.checkparam');
requests.ask('me', {}, 1001);
requests.sent(0, 'me');
requests.ask('me', { pdif_expected = player.pdif_inputs() }, 1001);
requests.on_reply(1, 712, 300, 1001, 558);
requests.on_reply(1, 715, 250, 1001, 365);
local values = { requests.values('me') };
expect('later enabling pDIF cannot invent the original request signature', values[8], nil);
expect('an unbound reused reply cannot populate the attack cache', player.accept_attacks(values[8], 558, 0, 0, 1), nil);
requests.reset();
MOCK.player.stats[0] = 'unreadable';
local unknown = player.pdif_inputs();
expect('unreadable inputs fail closed', unknown.signature, nil);
expect('unreadable inputs have no attack', unknown.attack, nil);
check('unreadable inputs explain the missing value', type(unknown.reason) == 'string');
MOCK.player.stats[0] = 60;
expect('snapshot reads do not send commands', #MOCK.commands, 0);
return MOCK.report();
