local player = require('core.player');
MOCK.items[10], MOCK.items[11], MOCK.items[12], MOCK.items[13] = { Skill = 3 }, { Skill = 2 }, { Skill = 25 }, { Skill = 0 };
MOCK.player.equipment = { [0] = 10, [1] = 11, [2] = 12, [3] = 13 };
MOCK.player.skills = { [2] = 120, [3] = 120, [25] = 120, [29] = 110 };
local values = { accuracy = 160, offhand_accuracy = 150, ranged_accuracy = 140, evasion = 130 };
local origin = player.parameter_inputs();
local snapshot = player.accept_parameters(origin, values, 42);
check('matching inputs accept a separate snapshot', snapshot ~= nil and snapshot ~= origin);
expect('accepting a reply leaves the request unchanged', origin.accuracy, nil);
expect('snapshot uses the server accuracy', snapshot.accuracy, 160);
expect('snapshot uses the separate off-hand accuracy', snapshot.offhand_accuracy, 150);
expect('snapshot uses the separate ranged accuracy', snapshot.ranged_accuracy, 140);
expect('snapshot uses the server evasion', snapshot.evasion, 130);
expect('snapshot records the reply time', snapshot.observed_at, 42);
values.accuracy = 1;
expect('snapshot does not retain the mutable reply table', snapshot.accuracy, 160);
values.accuracy = 160;
local valid, reason, conditional = player.parameters_valid(snapshot);
check('unchanged snapshot remains valid without uncertainty', valid and reason == nil and not conditional);

local function rejects(label, mutate, restore)
    local expected = player.parameter_inputs();
    local saved = player.accept_parameters(expected, values, 42);
    mutate();
    expect(label .. ' invalidates a saved snapshot', player.parameters_valid(saved), false);
    local accepted, why = player.accept_parameters(expected, values, 43);
    expect(label .. ' rejects a pending reply', accepted, nil);
    check(label .. ' explains the rejection', type(why) == 'string' and why:find('Check again', 1, true));
    restore();
end
rejects('DEX change', function() MOCK.player.stats[1] = 71; end, function() MOCK.player.stats[1] = 70; end);
rejects('AGI modifier change', function() MOCK.player.stat_mods[3] = 1; end, function() MOCK.player.stat_mods[3] = nil; end);
rejects('Evasion skill change', function() MOCK.player.skills[29] = 111; end, function() MOCK.player.skills[29] = 110; end);
rejects('weapon skill change', function() MOCK.player.skills[3] = 121; end, function() MOCK.player.skills[3] = 120; end);
rejects('buff change', function() MOCK.player.buffs = { 56 }; end, function() MOCK.player.buffs = {}; end);
rejects('equipment change', function() MOCK.player.equipment[1] = nil; end, function() MOCK.player.equipment[1] = 11; end);
rejects('character change', function() MOCK.player.server_id = 1002; end, function() MOCK.player.server_id = 1001; end);
rejects('zone change', function() MOCK.player.zone = 104; end, function() MOCK.player.zone = 103; end);
rejects('job change', function() MOCK.player.main_job = 1; end, function() MOCK.player.main_job = 4; end);
rejects('level change', function() MOCK.player.main_level = 74; end, function() MOCK.player.main_level = 75; end);
local memory, extra = AshitaCore:GetMemoryManager(), 'old augment';
local inventory = memory.GetInventory;
memory.GetInventory = function(...)
    local bag = inventory(...);
    local get = bag.GetContainerItem;
    bag.GetContainerItem = function(...)
        local item = get(...);
        item.Extra = extra;
        return item;
    end;
    return bag;
end;
rejects('same-item augment change', function() extra = 'new augment'; end, function() extra = 'old augment'; end);
memory.GetInventory = inventory;

origin = player.parameter_inputs();
MOCK.player.hp = 900;
snapshot = player.accept_parameters(origin, values, 44);
check('HP changes during a request retain its completed readings', snapshot ~= nil);
check('HP changes during a request qualify its conditional bonuses', snapshot.condition_changed);
MOCK.player.hp = 1000;
origin = player.parameter_inputs();
snapshot = player.accept_parameters(origin, values, 45);
MOCK.player.tp = 100;
valid, reason, conditional = player.parameters_valid(snapshot);
check('TP changes retain the snapshot with uncertainty', valid and conditional and reason == nil);
MOCK.player.tp = 0;
MOCK.player.hp_max = 1100;
valid, reason, conditional = player.parameters_valid(snapshot);
check('max HP changes retain the snapshot with uncertainty', valid and conditional);
MOCK.player.hp_max = 1000;
snapshot = player.accept_parameters(player.parameter_inputs(), { accuracy = 160, offhand_accuracy = 0 }, 46);
expect('missing evasion stays unknown', snapshot.evasion, nil);
expect('zero off-hand stays unknown', snapshot.offhand_accuracy, nil);
expect('missing ranged accuracy stays unknown', snapshot.ranged_accuracy, nil);
expect('an empty reply has no snapshot', player.accept_parameters(player.parameter_inputs(), {}, 46), nil);
expect('an unbound reply has no snapshot', player.accept_parameters(nil, values, 46), nil);
expect('nonfinite values have no snapshot', player.accept_parameters(player.parameter_inputs(), {
    accuracy = 0 / 0, evasion = math.huge, ranged_accuracy = -1 }, 46), nil);
MOCK.player.stats[1] = 'unreadable';
expect('unreadable current stats have no usable signature', player.parameter_inputs().signature, nil);
expect('unreadable current stats reject a reply', player.accept_parameters(origin, values, 46), nil);
MOCK.player.stats[1] = 70;

addon.path = FIXTURES_PATH;
local target = require('core.target');
local physical = require('core.physical');
local effects = require('core.effects');
local s = require('ui.defaults').make();
for id in pairs(s.overlay.parts) do s.overlay.parts[id] = false; end
s.overlay.parts.hit, s.overlay.parts.offhand, s.overlay.parts.ranged, s.overlay.parts.evade = true, true, true, true;
MOCK.player.zone, MOCK.player.main_level = 900, 40;
MOCK.target_monster(1, 'Fixture Goblin');
local id = MOCK.mob_id(900, 1);
local version = 0;
effects.version = function() return version; end;
effects.readout = function() return nil; end;
local reads, original_inputs = 0, player.parameter_inputs;
player.parameter_inputs = function(...)
    reads = reads + 1;
    return original_inputs(...);
end;
local function frame(seconds)
    MOCK.now = MOCK.now + (seconds or 0);
    target.take_in();
    target.read(s.overlay);
    return target.readout(s);
end
target.on_zone(900);
local result = frame();
expect('passive target starts without accuracy', result.hit, nil);
expect('passive target starts without evasion', result.evade, nil);
expect('passive target has not requested stats', result.provenance.parameter_state, 'not_requested');
local token = 1;
local function checked(index, reply)
    index, reply = index or 1, reply or values;
    token = token + 1;
    local target_id = MOCK.mob_id(900, index);
    target.on_check(index, target_id, 39, 4, 2, nil, false, token, 'waiting');
    local accepted = player.accept_parameters(player.parameter_inputs(), reply, MOCK.now);
    target.on_parameters(index, target_id, token, accepted);
    return accepted, token;
end
snapshot = checked();
result = frame();
check('completed matching reply populates all four rows', result.hit and result.offhand and result.ranged and result.evade);
expect('accepted provenance uses the shared received state', result.provenance.parameter_state, 'received');
expect('accepted provenance keeps the reply time', result.provenance.parameter_at, snapshot.observed_at);
expect('received parameters have no invented missing-reading reason', result.parameter_reason, nil);
expect('current inputs include the observed accuracy', result.inputs.accuracy, 160);
check('off-hand and ranged use their own accuracy values', result.hit.low ~= result.offhand.low and result.offhand.low ~= result.ranged.low);
local earlier, before = result, reads;
local quiet, changed = frame(0.1);
expect('quiet frame reuses the same readout', quiet, earlier);
expect('quiet frame does not rebuild', changed, false);
expect('quiet frame does not poll parameter inputs', reads, before);
frame(0.2);
expect('a due poll reads the signature only once', reads, before + 1);
MOCK.player.tp = 100;
result = frame(0.3);
check('TP changes preserve the four estimates', result.hit and result.offhand and result.ranged and result.evade);
check('TP changes qualify all four estimates', result.hit.uncertain and result.offhand.uncertain and result.ranged.uncertain and result.evade.uncertain);
check('conditional qualification gives the concrete reason', table.concat(result.hit.notes, ' '):find('HP or TP changed', 1, true));
expect('new uncertainty does not mutate the older readout', earlier.hit.uncertain, nil);
MOCK.player.tp = 0;
result = frame(0.3);
check('returning TP does not erase observed conditional uncertainty', result.hit.uncertain);
checked();
result = frame();
expect('a new matching reading clears old conditional uncertainty', result.hit.uncertain, nil);

MOCK.target_monster(2, 'Fixture Goblin');
result = frame();
expect('another target cannot borrow the first target accuracy', result.hit, nil);
checked(2);
result = frame();
check('a separate matching check populates the new target', result.hit ~= nil);
MOCK.player.stats[1] = 71;
result = frame(0.3);
check('stable input change retains the visible reading as an older estimate', result.hit and result.hit.retained);
expect('stable input change has a stale state', result.provenance.parameter_state, 'stale');
check('stable input change explains how to refresh', result.parameter_reason:find('Check again', 1, true));
MOCK.player.stats[1] = 70;
MOCK.target_monster(1, 'Fixture Goblin');
result = frame(0.3);
check('an observed change also marks other kept target readings', result.hit and result.hit.retained);
expect('restoring inputs cannot revive an old target reading', result.provenance.parameter_state, 'stale');
local old, old_token = checked();
result = frame();
token = token + 1;
target.on_check(1, id, 39, 4, 2, nil, false, token, 'waiting');
result = frame();
expect('new check clears the previous reading while waiting', result.hit, nil);
expect('new check preserves the actual waiting state', result.provenance.parameter_state, 'waiting');
target.on_parameters(1, id, old_token, old);
result = frame();
expect('late reply for the previous check cannot attach', result.hit, nil);
target.on_parameters(1, id, token, nil, 'The reply timed out. Check again.');
result = frame();
expect('failed matching reply remains unavailable', result.provenance.parameter_state, 'unavailable');
expect('failed reply has no invented observation time', result.provenance.parameter_at, nil);
checked(1, { accuracy = 160 });
result = frame();
check('completed partial reply can populate its known field', result.hit ~= nil);
expect('completed partial reply leaves evasion unknown', result.evade, nil);
expect('completed partial reply leaves off-hand unknown', result.offhand, nil);
expect('completed partial reply leaves ranged unknown', result.ranged, nil);

local observed_mob, read_physical = nil, physical.readout;
physical.readout = function(me, mob) observed_mob = mob; return read_physical(me, mob); end;
checked();
result = frame();
expect('matching snapshot carries the kept difficulty into physical math', observed_mob.con, 4);
expect('matching snapshot carries the kept evasion reading into physical math', observed_mob.reading, 2);
physical.readout = read_physical;
s.ranged.show_distance = true;
MOCK.entities[1].Distance = 100;
target.mark_stale();
result = frame();
expect('ranged distance uses the shared structured shape', result.ranged_distance.distance, 10);
local ranged_hit = result.ranged.low;
MOCK.entities[1].Distance = 144;
result = frame(0.3);
expect('the enabled distance refreshes on the regular poll', result.ranged_distance.distance, 12);
expect('distance does not silently adjust the sweet-spot estimate', result.ranged.low, ranged_hit);
MOCK.entities[1].Distance = nil;
result = frame(0.3);
expect('unreadable distance stays absent', result.ranged_distance, nil);
s.ranged.show_distance = false;
target.mark_stale();
result = frame();
earlier = result;
version = version + 1;
result = frame();
check('effect changes also rebuild the four physical rows', result ~= earlier);
MOCK.player.stats[3] = 66;
version = version + 1;
result = frame();
check('effect-triggered rebuild keeps the older result instead of mixing changed inputs', result.hit
    and result.hit.retained and result.hit.low == earlier.hit.low);
MOCK.player.stats[3] = 65;

old, old_token = checked();
frame();
target.on_disappear(id, 1);
target.on_parameters(1, id, old_token, old);
result = frame();
expect('disappearance prevents a queued old reply from reattaching', result.hit, nil);
old, old_token = checked();
frame();
target.on_zone(900);
target.on_parameters(1, id, old_token, old);
result = frame();
expect('zone reset prevents a queued old reply from reattaching', result.hit, nil);
checked();
frame();
s.overlay.remember = false;
MOCK.target_monster(2, 'Fixture Goblin');
frame();
MOCK.target_monster(1, 'Fixture Goblin');
result = frame();
expect('Remember off discards checked readings on target change', result.hit, nil);
s.overlay.remember = true;
checked();
frame();
target.on_death(1);
expect('a dead target cannot retain displayed readings', frame(), nil);
MOCK.target_monster(2, 'Fixture Goblin');
frame();
MOCK.target_monster(1, 'Fixture Goblin');
result = frame();
expect('retargeting the same ID cannot resurrect a dead target snapshot', result.hit, nil);
for part in pairs(s.overlay.parts) do s.overlay.parts[part] = false; end
target.mark_stale();
frame();
before = reads;
frame(1);
expect('disabled parameter rows do not poll the snapshot signature', reads, before);
expect('the full target cache flow sends no requests', #MOCK.commands, 0);
player.parameter_inputs = original_inputs;
target.forget();
return MOCK.report();
