-- Rogue's Ring needs base HP, which displayed HP and an active sync cannot establish.
dofile(ADDON_DIR .. '/checkmate.lua');
MOCK.fire('load');
local steal = require('core.steal');
local player = require('core.player');
local printout = require('core.printout');
local tips = require('ui.tips');
local s = MOCK.settings.current;
MOCK.items[864] = { Name = { 'Fish Scales' } };
MOCK.player.main_job, MOCK.player.main_level = 6, 75;
MOCK.player.sub_job, MOCK.player.sub_level = 13, 37;
MOCK.player.equipment = { [4] = 12514, [6] = 12748, [7] = 15585, [8] = 15357, [9] = 13112, [13] = 13291 };
MOCK.player.hp, MOCK.player.hp_max, MOCK.player.tp = 760, 1038, 0;
local function read(low, high)
    local p = MOCK.player;
    local me = steal.you(p.main_job, p.main_level, p.sub_job, p.sub_level);
    return steal.readout({ steal = { 864 } }, me, low or 58, high or low or 58);
end
local r = read();
check('displayed HP cannot choose the ring bonus', r.low == 91 and r.high == 97 and r.uncertain == true,
    tostring(r.low) .. '-' .. tostring(r.high));
expect('chat shows the uncertain range', printout.number_text(r, 'range'), '~91-97%');
check('the tooltip names the missing base HP', tips.text(s, { steal = r }, 'steal', '864'):find('base max HP', 1, true) ~= nil);
check('the midpoint keeps one estimate mark', printout.number_text(r, 'midpoint') == '~94%');
r = read(57, 60);
check('monster levels and uncertain ring bonus combine', r.low == 89 and r.high == 98);
MOCK.player.tp = 1000;
r = read();
check('100% TP excludes the ring even with unknown HP', r.low == 91 and r.high == 91 and not r.uncertain);
MOCK.player.tp = 0;
MOCK.packet(MOCK.job_info_packet(1000));
r = read();
check('known base HP excludes a false displayed-HP bonus', r.low == 91 and r.high == 91 and not r.uncertain);
MOCK.player.hp = 750;
r = read();
check('known base HP includes the exact threshold', r.low == 97 and r.high == 97 and not r.uncertain);
MOCK.player.buffs = { 269 };
r = read();
check('Level Sync can leave known base HP stale', r.low == 91 and r.high == 97 and r.uncertain == true);
check('the tooltip explains the sync limit', tips.text(s, { steal = r }, 'steal', '864'):find('Level Sync', 1, true) ~= nil);
MOCK.player.tp = 1000;
r = read();
check('TP excludes the ring during sync too', r.low == 91 and r.high == 91 and not r.uncertain);
MOCK.player.tp = 0;
MOCK.player.main_level = 49;
r = read();
check('below level 50 the ring stays excluded', r.low == 43 and r.high == 43 and not r.uncertain);
MOCK.player.main_level = 75;
MOCK.player.equipment[13] = nil;
r = read();
check('sync does not qualify a chance with no ring', r.low == 91 and r.high == 91 and not r.uncertain);
MOCK.player.equipment[13] = 13291;
r = read(1);
check('an uncertain bonus does not qualify a guaranteed roll', r.low == 100 and r.high == 100 and not r.uncertain);
MOCK.player.buffs = {};
player.on_base_hp(nil);
MOCK.player.hp_max = 1000;
player.inputs_changed();
check('an unchanged snapshot stays quiet', not player.inputs_changed());
MOCK.packet(MOCK.job_info_packet(1000));
check('observing equal base HP still changes the input certainty', player.inputs_changed());
check('that certainty change only refreshes once', not player.inputs_changed());
-- An equal-valued base HP message still replaces the overlay's uncertain result.
MOCK.zone_in(176);
MOCK.player.hp, MOCK.player.hp_max, MOCK.player.tp = 760, 1000, 0;
MOCK.command('/checkmate overlay on');
MOCK.command('/checkmate overlayshow steal');
MOCK.command('/checkmate show steal');
MOCK.target_monster(289, 'Razorjaw Pugil');
local before = #MOCK.printed;
MOCK.packet(MOCK.check_packet(289, 58, 4, 174));
MOCK.frame(0.3);
check('the actual chat line shows both outcomes', table.concat(MOCK.printed_since(before), '\n')
    :find('Steal: Fish Scales (~91-97%) (conditional)', 1, true) ~= nil);
local target = require('core.target');
r = target.current().steal;
check('the selected target starts with both Ring outcomes', r.low == 91 and r.high == 97 and r.uncertain);
MOCK.packet(MOCK.job_info_packet(1000));
MOCK.frame(0.3);
r = target.current().steal;
check('observed base HP refreshes without retargeting', r.low == 91 and r.high == 91 and not r.uncertain);
MOCK.player.buffs = { 269 };
MOCK.frame(0.3);
r = target.current().steal;
check('entering Level Sync refreshes the Ring uncertainty', r.low == 91 and r.high == 97 and r.uncertain);
local current = target.current();
MOCK.frame(0.01);
check('a quiet frame keeps that readout', target.current() == current);
MOCK.player.equipment[13] = nil;
MOCK.frame(0.3);
r = target.current().steal;
check('taking off the Ring clears its uncertainty', r.low == 91 and r.high == 91 and not r.uncertain);
expect('these passive updates send no game commands', #MOCK.commands, 0);
return MOCK.report();
