package.loaded['data.pdif'] = { melee_cap = 2, ranged_cap = 3,
    melee_level_step = 3 / 64, ranged_level_step = 3 / 128, max_level_gap = 38,
    level_corrected_zones = { [900] = true }, defense_effects = { [33] = 'Dia' } };
addon.path = FIXTURES_PATH;
local target = require('core.target');
local player = require('core.player');
local monsters = require('core.monsters');
local effects = require('core.effects');
local s = require('ui.defaults').make();
for id in pairs(s.overlay.parts) do s.overlay.parts[id] = false; end
s.overlay.parts.pdif, s.overlay.parts.offhandpdif, s.overlay.parts.rangedpdif = true, true, true;
MOCK.player.zone, MOCK.player.main_level = 900, 40;
MOCK.items[10], MOCK.items[11], MOCK.items[12], MOCK.items[13] = { Skill = 3 }, { Skill = 2 }, { Skill = 25 }, { Skill = 0 };
MOCK.player.equipment = { [0] = 10, [1] = 11, [2] = 12, [3] = 13 };
MOCK.target_monster(1, 'Fixture Goblin');
local version, observed = 0, nil;
effects.version = function() return version; end;
effects.readout = function() return observed; end;
target.on_zone(900);
target.take_in();
target.read(s.overlay);
local row = monsters.find(900, MOCK.mob_id(900, 1), 'Fixture Goblin');
for level, stats in pairs(row.levels) do stats.def = level * 10; end
local result = target.readout(s);
expect('pDIF overlay starts unknown without a server attack reply', result.pdif.low, nil);
expect('passive pDIF overlay sends no commands', #MOCK.commands, 0);
local saved = player.accept_attacks(player.pdif_inputs(), 558, 510, 610, MOCK.now);
MOCK.now = MOCK.now + 0.3;
result = target.readout(s);
expect('overlay notices a newly accepted main attack', result.pdif.attack, 558);
expect('overlay uses the separate off-hand attack', result.offhandpdif.attack, 510);
expect('overlay uses the separate ranged attack', result.rangedpdif.attack, 610);
check('overlay computes main multiplier with source defense', result.pdif.low ~= nil);
expect('overlay preserves reply timestamp', result.pdif.observed_at, saved.observed_at);
local snapshot = result;
MOCK.now = MOCK.now + 0.1;
local quiet, changed = target.readout(s);
expect('quiet frames reuse the readout', quiet, snapshot);
expect('quiet frames do not rebuild', changed, false);
version, observed = 1, { { effect = 33 } };
result = target.readout(s);
check('observed defense changes invalidate the pDIF readout', result ~= snapshot);
check('observed defense effects retain their qualification', table.concat(result.pdif.notes, ' '):find('Dia was seen', 1, true));
MOCK.player.buffs = { 56 };
MOCK.now = MOCK.now + 0.3;
result = target.readout(s);
expect('changed buffs invalidate the attack snapshot in the overlay', result.pdif.low, nil);
expect('the old readout stays a snapshot', snapshot.pdif.attack, 558);
expect('changed inputs never trigger an automatic request', #MOCK.commands, 0);
player.accept_attacks(player.pdif_inputs(), 600, 550, 650, MOCK.now);
MOCK.player.equipment[1], MOCK.player.equipment[2], MOCK.player.equipment[3] = nil, nil, nil;
MOCK.now = MOCK.now + 0.3;
result = target.readout(s);
expect('removed off-hand has no pDIF line', result.offhandpdif, nil);
expect('removed ranged gear has no pDIF line', result.rangedpdif, nil);
expect('weapon removal also invalidates main attack', result.pdif.attack, nil);
target.on_death(1);
target.take_in();
expect('a dead target leaves no pDIF display', target.readout(s), nil);
target.forget();
player.forget_attacks();
expect('the entire passive flow sent no commands', #MOCK.commands, 0);
return MOCK.report();
