-- A selected target must follow local inputs without sending another command or losing its check snapshot.
local defaults = require('ui.defaults');
local player = require('core.player');
local target = require('core.target');
local monsters = require('core.monsters');
local diagnostics = require('core.diagnostics');
local s = defaults.make();
addon.path = FIXTURES_PATH;
MOCK.player.zone, MOCK.player.main_level = 900, 40;
MOCK.target_monster(1, 'Fixture Goblin');
s.overlay.on, s.overlay.parts.crit, s.overlay.parts.magic = true, true, true;
target.on_zone(900);
target.take_in();
target.read(s.overlay);
local first = target.readout(s);
expect('an unchecked level comes from spawn data', first.provenance.level_source, 'spawn');
target.on_check(1, MOCK.mob_id(900, 1), 39, 4, 1, 1, false);
target.take_in();
local checked = target.readout(s);
expect('a checked level says where it came from', checked.provenance.level_source, 'check');
local observed = checked.provenance.observed_at;
local before = checked.crit.high;
MOCK.player.stat_mods[1] = 100;
MOCK.now = MOCK.now + 0.3;
local changed, rebuilt = target.readout(s);
check('a DEX change refreshes the selected target', rebuilt and changed.crit.high > before);
expect('refresh keeps the actual check observation time', changed.provenance.observed_at, observed);
check('refresh stamps its new inputs', changed.provenance.inputs_at > checked.provenance.inputs_at);
local same, rebuilt_again = target.readout(s);
check('a quiet frame keeps the cached readout', same == changed and not rebuilt_again);
MOCK.player.buffs[1] = 2;
MOCK.now = MOCK.now + 0.3;
local buffed, buff_rebuilt = target.readout(s);
check('a buff change also refreshes', buff_rebuilt and buffed ~= same);
MOCK.player.hp = 700;
MOCK.player.tp = 1100;
MOCK.now = MOCK.now + 0.3;
local hp_changed, hp_rebuilt = target.readout(s);
check('HP and TP changes are noticed for latent equipment', hp_rebuilt and hp_changed ~= buffed);
MOCK.player.equipment[5] = 14505;
MOCK.now = MOCK.now + 0.3;
local equipped, gear_rebuilt = target.readout(s);
check('a gear change also refreshes without changing targets', gear_rebuilt and equipped ~= hp_changed);
expect('none of these local refreshes sends a command', #MOCK.commands, 0);

MOCK.entities[1].Distance = 144;
expect('distance uses the square root of the client reading', player.distance(1), 12);
MOCK.entities[1].Distance = -1;
expect('an invalid distance stays unknown', player.distance(1), nil);
MOCK.entities[1].Distance = 0/0;
expect('NaN distance stays unknown', player.distance(1), nil);

monsters.on_widescan(1, 39);
expect('widescan records its source', monsters.level_source(nil, 0, 1), 'widescan');
monsters.on_death(1);
expect('a seen death clears an old widescan level', monsters.level_source(nil, 0, 1), 'unknown');
target.on_death(1);
target.take_in();
expect('a seen death hides that target', target.readout(s), nil);

addon.path = ADDON_PATH;
monsters.preload(103);
local summary = diagnostics.text('1.3.0');
check('diagnostics describe the bundled source boundary', summary:find('do not verify the running server', 1, true) ~= nil);
check('real bundled revisions agree', summary:find('Bundled data revisions and content settings match.', 1, true) ~= nil, summary);
addon.path = FIXTURES_PATH;
local mixed = diagnostics.text('1.3.0');
check('missing or mixed bundles are visible', mixed:find('Mixed or missing data files:', 1, true) ~= nil, mixed);
return MOCK.report();
